version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: >-
    Write-Host "$env:APPVEYOR_REPO_TAG_NAME"

    $manPath = Resolve-Path .\Framework.VSIX\source.extension.vsixmanifest

    [Xml] $manifest = Get-Content $manPath

    $manifest.PackageManifest.Metadata.Identity.Version = "$env:APPVEYOR_REPO_TAG_NAME"

    $manifest.Save($manPath)


    nuget restore
build:
  verbosity: minimal
artifacts:
- path: Framework.VSIX\bin\$(configuration)\Framework.VSIX.vsix
deploy:
- provider: GitHub
  release: v$(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: zK12v9qF0HKPG0fqWlWh8nEnjXQFRTsYXm4HTNCIFMwKlcKgfEGesEpe1uPlqMIt
  artifact: Framework.VSIX\bin\$(configuration)\Framework.VSIX.vsix
  draft: true
  on:
    branch:master
    appveyor_repo_tag: true 